#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

export GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"

mode="prebuild"
if [[ $# -gt 0 ]]; then
  case "$1" in
    --prebuild|prebuild)
      mode="prebuild"
      ;;
    --light|light)
      mode="light"
      ;;
    -h|--help)
      cat <<'USAGE'
Usage: bash scripts/dev/bootstrap-prebuild.sh [--prebuild|--light]

Modes:
  --prebuild  Warm Node, TypeScript, NeoForge/Gradle caches, dev runtime files, and docs guards.
  --light     Prepare a normal devcontainer quickly without running the NeoForge Gradle warmup.
USAGE
      exit 0
      ;;
    *)
      echo "Unknown bootstrap mode: $1" >&2
      exit 2
      ;;
  esac
fi

log() {
  printf '[minelink-prebuild] %s\n' "$*"
}

run() {
  log "+ $*"
  "$@"
}

install_os_packages() {
  if ! command -v apt-get >/dev/null 2>&1; then
    log "apt-get not found; skipping OS package installation"
    return
  fi

  local missing=()
  for command_name in curl ffmpeg git Xvfb python3; do
    if ! command -v "$command_name" >/dev/null 2>&1; then
      missing+=("$command_name")
    fi
  done
  if command -v python3 >/dev/null 2>&1 && ! python3 -c 'import PIL' >/dev/null 2>&1; then
    missing+=("python3-pil")
  fi

  if [[ ${#missing[@]} -eq 0 ]]; then
    log "required OS tools already present; skipping apt-get install"
    return
  fi

  log "missing OS tools: ${missing[*]}; installing bootstrap packages"

  local sudo_cmd=()
  if [[ "$(id -u)" -ne 0 ]]; then
    sudo_cmd=(sudo)
  fi

  run "${sudo_cmd[@]}" apt-get update
  run "${sudo_cmd[@]}" apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    ffmpeg \
    git \
    libasound2 \
    libgl1 \
    libgl1-mesa-dri \
    libxcursor1 \
    libxi6 \
    libxinerama1 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    libxxf86vm1 \
    python3 \
    python3-pil \
    xvfb
}

check_runtime_versions() {
  log "bootstrap mode: $mode"
  log "devcontainer image: ${MINELINK_DEVCONTAINER_IMAGE:-unreported}"
  log "Gradle user home: $GRADLE_USER_HOME"
  run node --version
  run npm --version
  run python3 --version
  run python3 -c 'import PIL; print("Pillow available")'
  run java -version
  run ffmpeg -version
  run bash -lc 'command -v Xvfb'
  if command -v gh >/dev/null 2>&1; then
    run gh --version
  else
    log "gh not found; GitHub CLI feature may not be installed"
  fi

  if [[ -n "${LINEAR_API_KEY:-}" ]]; then
    log "LINEAR_API_KEY present"
  else
    log "LINEAR_API_KEY missing; Linear sync will be skipped until the Ona secret is attached"
  fi
}

report_cache_state() {
  local npm_cache="$HOME/.npm"
  local gradle_modules="$GRADLE_USER_HOME/caches/modules-2"
  local gradle_transforms="$GRADLE_USER_HOME/caches/transforms-4"

  if [[ -d "$npm_cache" ]]; then
    log "npm cache present at $npm_cache"
  else
    log "npm cache missing at $npm_cache; npm ci will cold-fill it"
  fi

  if [[ -d "$gradle_modules" ]]; then
    log "Gradle module cache present at $gradle_modules"
  else
    log "Gradle module cache missing at $gradle_modules; Gradle will cold-fill it"
  fi

  if [[ -d "$gradle_transforms" ]]; then
    log "Gradle transform cache present at $gradle_transforms"
  else
    log "Gradle transform cache missing at $gradle_transforms; NeoForge userdev may run cold transforms"
  fi
}

warm_node_workspace() {
  if [[ "$mode" == "light" ]]; then
    if [[ -d node_modules ]]; then
      log "node_modules present; skipping npm ci in light bootstrap"
    else
      run npm ci --prefer-offline
    fi
    return
  fi

  run npm ci
  run npm run build
  run npm run typecheck
}

warm_neoforge_workspace() {
  if [[ "$mode" == "light" ]]; then
    log "light bootstrap; skipping Gradle/NeoForge cache warmup"
    return
  fi

  if [[ "${MINELINK_PREBUILD_SKIP_GRADLE:-0}" == "1" ]]; then
    log "MINELINK_PREBUILD_SKIP_GRADLE=1; skipping Gradle/NeoForge cache warmup"
    return
  fi

  pushd mod/neoforge >/dev/null
  run ./gradlew --no-daemon --version
  run ./gradlew --no-daemon build
  run ./gradlew --no-daemon prepareClientRun downloadAssets
  popd >/dev/null
}

prepare_dev_minecraft_runtime() {
  mkdir -p mod/neoforge/run
  printf '%s\n' \
    '# Generated by MineLink Ona/devcontainer prebuild for authorized development validation.' \
    'eula=true' > mod/neoforge/run/eula.txt

  if [[ ! -f mod/neoforge/run/server.properties ]]; then
    printf '%s\n' \
      '# Generated by MineLink Ona/devcontainer prebuild for local agent validation.' \
      'online-mode=false' > mod/neoforge/run/server.properties
  elif grep -Eq '^online-mode\s*=' mod/neoforge/run/server.properties; then
    sed -E 's/^online-mode\s*=.*/online-mode=false/' \
      mod/neoforge/run/server.properties > mod/neoforge/run/server.properties.tmp
    mv mod/neoforge/run/server.properties.tmp mod/neoforge/run/server.properties
  else
    printf '\n%s\n' 'online-mode=false' >> mod/neoforge/run/server.properties
  fi

  log "prepared dev-only Minecraft EULA and offline server properties under ignored mod/neoforge/run/"
}

run_repo_guards() {
  run bash scripts/dev/verify-agent-task.sh --scope docs
}

prune_checkout_outputs_for_snapshot() {
  if [[ "$mode" != "prebuild" ]]; then
    return
  fi

  if [[ "${MINELINK_PREBUILD_KEEP_OUTPUTS:-0}" == "1" ]]; then
    log "MINELINK_PREBUILD_KEEP_OUTPUTS=1; keeping checkout-local build outputs"
    return
  fi

  rm -rf .gradle mod/neoforge/.gradle mod/neoforge/build
  if [[ -d mod/neoforge/run ]]; then
    find mod/neoforge/run -mindepth 1 -maxdepth 1 \
      ! -name eula.txt \
      ! -name server.properties \
      -exec rm -rf {} +
  fi

  log "pruned checkout-local build outputs before Ona snapshot; user-home npm/Gradle caches remain warm"
}

install_os_packages
check_runtime_versions
report_cache_state
warm_node_workspace
warm_neoforge_workspace
prepare_dev_minecraft_runtime
run_repo_guards
prune_checkout_outputs_for_snapshot

log "prebuild bootstrap complete"
