#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

runtime="${MINELINK_RUNTIME:-mock}"
port="${MINELINK_PORT:-25575}"
fixture="${MINELINK_FIXTURE:-vanilla_tree}"
log_dir="${MINELINK_LOG_DIR:-.minelink-dev/logs}"
trace="${MINELINK_TRACE:-.minelink-dev/replays/latest-action-trace.jsonl}"
require_eula="${MINELINK_REQUIRE_EULA:-0}"
accept_eula="${MINELINK_ACCEPT_EULA:-1}"
online_mode="${MINELINK_ONLINE_MODE:-false}"
minecraft_port="${MINELINK_MINECRAFT_PORT:-}"
level_name="${MINELINK_MINECRAFT_LEVEL_NAME:-world}"
ref_ttl_ms="${MINELINK_REF_TTL_MS:-}"
enable_create="${MINELINK_ENABLE_CREATE:-0}"
gradle_cmd="${MINELINK_GRADLE_CMD:-}"

upsert_server_property() {
  key="$1"
  value="$2"
  file="$3"
  if [ ! -f "$file" ]; then
    printf '%s\n' '# Generated by MineLink dev harness for local agent validation.' "$key=$value" > "$file"
  elif grep -Eq "^${key}\\s*=" "$file"; then
    tmp_properties="${file}.$$.$RANDOM.tmp"
    sed -E "s/^${key}\\s*=.*/$key=$value/" "$file" > "$tmp_properties"
    mv "$tmp_properties" "$file"
  else
    printf '\n%s\n' "$key=$value" >> "$file"
  fi
}

mkdir -p "$log_dir" "$(dirname "$trace")"

if [ "$runtime" = "mock" ]; then
  if [ -n "$ref_ttl_ms" ]; then
    exec node packages/mock-runtime/dist/index.js \
      --fixture "$fixture" \
      --port "$port" \
      --log-dir "$log_dir" \
      --trace "$trace" \
      --ref-ttl-ms "$ref_ttl_ms"
  fi
  exec node packages/mock-runtime/dist/index.js \
    --fixture "$fixture" \
    --port "$port" \
    --log-dir "$log_dir" \
    --trace "$trace"
fi

if [ "$runtime" = "neoforge" ]; then
  mkdir -p mod/neoforge/run
  if [ "$accept_eula" = "1" ] || [ "$accept_eula" = "true" ]; then
    printf '%s\n' '# Generated by MineLink dev harness for local Minecraft validation.' 'eula=true' > mod/neoforge/run/eula.txt
  elif [ "$require_eula" = "1" ] || [ "$require_eula" = "true" ]; then
    if [ ! -f mod/neoforge/run/eula.txt ] || ! grep -q '^eula=true' mod/neoforge/run/eula.txt; then
      echo "Minecraft EULA has not been accepted in mod/neoforge/run/eula.txt." >&2
      echo "Set MINELINK_ACCEPT_EULA=1 for local test automation or create the file yourself." >&2
      exit 1
    fi
  fi

  server_properties="mod/neoforge/run/server.properties"
  upsert_server_property "online-mode" "$online_mode" "$server_properties"
  upsert_server_property "level-name" "$level_name" "$server_properties"
  if [ -n "$minecraft_port" ]; then
    upsert_server_property "server-port" "$minecraft_port" "$server_properties"
  fi

  if command -v /usr/libexec/java_home >/dev/null 2>&1; then
    java21_home="$(/usr/libexec/java_home -v 21 2>/dev/null || true)"
    if [ -n "$java21_home" ]; then
      export JAVA_HOME="$java21_home"
      export PATH="$JAVA_HOME/bin:$PATH"
    fi
  fi

  if ! command -v java >/dev/null 2>&1; then
    echo "Java 21 is required to start the NeoForge dev server." >&2
    exit 1
  fi
  java_major="$(java -version 2>&1 | head -n 1 | sed -E 's/.*version "([0-9]+).*/\1/')"
  if [ "${java_major:-0}" -lt 21 ] 2>/dev/null; then
    echo "Java 21 is required for NeoForge 1.21.1; current java -version is:" >&2
    java -version >&2
    exit 1
  fi
  if [ ! -x mod/neoforge/gradlew ]; then
    echo "mod/neoforge/gradlew is missing. Add a Gradle wrapper before running the real NeoForge server." >&2
    exit 1
  fi
  if [ "$enable_create" = "1" ] || [ "$enable_create" = "true" ]; then
    if [ -n "$gradle_cmd" ]; then
      (cd mod/neoforge && exec "$gradle_cmd" --no-daemon -PenableCreateAdapter=true runServer)
    else
      (cd mod/neoforge && exec ./gradlew --no-daemon -PenableCreateAdapter=true runServer)
    fi
    exit $?
  fi
  if [ -n "$gradle_cmd" ]; then
    (cd mod/neoforge && exec "$gradle_cmd" --no-daemon runServer)
    exit $?
  else
    (cd mod/neoforge && exec ./gradlew --no-daemon runServer)
    exit $?
  fi
fi

echo "Unknown MINELINK_RUNTIME=$runtime" >&2
exit 2
