#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

runtime="${MINELINK_RUNTIME:-mock}"
port="${MINELINK_PORT:-25575}"
fixture="${MINELINK_FIXTURE:-vanilla_tree}"
log_dir="${MINELINK_LOG_DIR:-.minelink-dev/logs}"
trace="${MINELINK_TRACE:-.minelink-dev/replays/latest-action-trace.jsonl}"
require_eula="${MINELINK_REQUIRE_EULA:-0}"
accept_eula="${MINELINK_ACCEPT_EULA:-1}"

mkdir -p "$log_dir" "$(dirname "$trace")"

if [ "$runtime" = "mock" ]; then
  exec node packages/mock-runtime/dist/index.js \
    --fixture "$fixture" \
    --port "$port" \
    --log-dir "$log_dir" \
    --trace "$trace"
fi

if [ "$runtime" = "neoforge" ]; then
  mkdir -p mod/neoforge/run
  if [ "$accept_eula" = "1" ] || [ "$accept_eula" = "true" ]; then
    printf '%s\n' '# Generated by MineLink dev harness for local Minecraft validation.' 'eula=true' > mod/neoforge/run/eula.txt
  elif [ "$require_eula" = "1" ] || [ "$require_eula" = "true" ]; then
    if [ ! -f mod/neoforge/run/eula.txt ] || ! grep -q '^eula=true' mod/neoforge/run/eula.txt; then
      echo "Minecraft EULA has not been accepted in mod/neoforge/run/eula.txt." >&2
      echo "Set MINELINK_ACCEPT_EULA=1 for local test automation or create the file yourself." >&2
      exit 1
    fi
  fi

  server_properties="mod/neoforge/run/server.properties"
  if [ ! -f "$server_properties" ]; then
    printf '%s\n' '# Generated by MineLink dev harness for local agent validation.' 'online-mode=false' > "$server_properties"
  elif grep -Eq '^online-mode\s*=' "$server_properties"; then
    tmp_properties="${server_properties}.tmp"
    sed -E 's/^online-mode\s*=.*/online-mode=false/' "$server_properties" > "$tmp_properties"
    mv "$tmp_properties" "$server_properties"
  else
    printf '\n%s\n' 'online-mode=false' >> "$server_properties"
  fi

  if ! command -v java >/dev/null 2>&1; then
    echo "Java 21 is required to start the NeoForge dev server." >&2
    exit 1
  fi
  java_major="$(java -version 2>&1 | head -n 1 | sed -E 's/.*version "([0-9]+).*/\1/')"
  if [ "${java_major:-0}" -lt 21 ] 2>/dev/null; then
    echo "Java 21 is required for NeoForge 1.21.1; current java -version is:" >&2
    java -version >&2
    exit 1
  fi
  if [ ! -x mod/neoforge/gradlew ]; then
    echo "mod/neoforge/gradlew is missing. Add a Gradle wrapper before running the real NeoForge server." >&2
    exit 1
  fi
  (cd mod/neoforge && exec ./gradlew runServer)
fi

echo "Unknown MINELINK_RUNTIME=$runtime" >&2
exit 2
